### PR TITLE
fix: remove dependence on libssl

### PR DESCRIPTION
**Pull request by KolbyML**

### CODE REVIEW

**Review by ogenev — APPROVED** [review]
⛵

**Comment by KolbyML** [comment]
What is the fix ``reqwest = { version = "0.11.6", default-features = false, features = ["rustls-tls"] }`` this is the fix it removes the need to use libssl3.

The reason why our images used ubuntu 20 is because 22 didn't provide libssl3. Now that we don't depend on libssl3 we can update to version 22.

**Comment by mrferris** [comment]
Do we not know why libssl3 is suddenly unavailable on the same ubuntu image? Guessing rust version but I don't see how that would change availability of a lib

**Comment by KolbyML** [comment]
We don't want to depend on libssl3 regardless as the library version isn't supported by default on new OS's. Personally I don't know why it became unavailable probably because of what you mentioned.

**Comment by KolbyML** [comment]
But yeah with the update to the rust container. It probably contained a different version of libssl which causes some kind of dynamic linker conflict when ran

**Pull request merged**
